displayName: Docker - Multiple Traefik
type: provider
iconPath: .assets/icon.png

import: github.com/leandrormd/dockerMultipleTraefik

summary: 'Docker - Multiple Traefik'

testData:
  labelPrefix: 'docker.multiple.traefik.test.'
